### ISSUE TITLE
Add pretty name for Cities

### ISSUE THREAD

**Issue by MoOx** [jpetitcolas/french-geography#1]
CITY & city are not just enough I think.
Why not add City (uppercase for first word) + accentuated letter (fake e.g. BITUME SUR PETIGNANT, bitume-sur-petignant, => Bitume sur Pétignant )

**Comment by jpetitcolas** [comment]
Indeed, seems a good idea. I think we can (should?) replace the _name_ field content with what you proposed. Indeed, it is easy to pass from "pretty name" to uppercase version, with _mb_strtoupper_ function for instance in PHP.

**Comment by jpetitcolas** [comment]
Fixed by cb95f3e1b048f405d016aad6e07515050edd276f.
