### ISSUE TITLE
Create build script from raw data

### ISSUE THREAD

**Issue by MoOx** [jpetitcolas/french-geography#2]
I've done this in the past (but can found it): I work with .csv file (sort of raw data) & have a build script which create sql & json version. It will be a good idea, especially toi maintain only one version of the data.

**Comment by MoOx** [comment]
Links to data
- http://www.alexandre-julien.com/base-de-donnees/listes-des-pays-regions-departements-et-villes-aux-formats-sql-csv-xls-et-xml/
- http://fr.wikipedia.org/wiki/Projet:Communes_de_France/Donn%C3%A9e
- http://www.bibichette.com/base-de-donnees-des-villes-francaise/
- http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement.asp
- http://www.blog.manit4c.com/2010/05/19/listes-utiles-au-format-csv/
- http://www.pillot.fr/cartographe/fic_villes.php
- http://www.france.comersis.com/base-de-donnees.php

It can be interesting to compare how many entries each files have to create the more complete file !

**Comment by jpetitcolas** [comment]
Or perhaps we should start from SQL format. It will be easier after to convert it in CSV for instance. Furthermore, we could deal very easily with all the data sources you gave.

Yet, I am wondering if there is any official complete list of cities. Perhaps from INSEE website? We should check if what they call "Commune" include every little village and so on.

http://www.insee.fr/fr/methodes/nomenclatures/cog/telechargement.asp/

I am not available this week-end, but I will try to give a check next week. Unless somebody else is faster than me. ;)

**Comment by MoOx** [comment]
In the past I found less city from Insee source than other ones. I never found an official source. But maybe a official website can be crawled :)

I'm not in a hurry too, I do not need this for now (but next month I will probably)

**Comment by ludofleury** [comment]
geoname give a csv with way too much data, but if you filter the csv by "populated places", you have something like 60K+ populated places in France. 

INSEE give the changelog (each year) and the official cities list for the France, yet there is no long/lat data and since INSEE has a some special format (removing prefix in the cities name for example) it could be tricky to add lgt / lat for each cities (crossing data with geoname)

**Comment by jpetitcolas** [comment]
I reviewed this project to ease the addition of format exports. It works with two main classes:
- **Parser:** which will read data from a datasource. Currently, it supports only INSEE one.
- **Formatter:** which turns the parsed data into a specified format. Currently, only SQL and YAML. But other should be very easy to implement now.

Which close current issue.

For the mixin between several datasources (especially for lat/long data), can you open a new issue @ludofleury?
